name: Build and Push Docker Image

on:
  push:
    branches:
      - main



jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: |
          pip install pytest
          pytest testfile.py -v
      
      - name: Build and push Docker image
        uses: docker/build-push-actions@v5
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/Bidemigrace-docker-ci-project
            ${{ secrets.DOCKER_USERNAME }}/Bidemigrace-docker-ci-project:${{ github.sha }}
